import { useCallback, useEffect, useState } from 'react';
import { api } from '../utils/api';
import type { Subscription } from '../components/sections/CustomerSubscriptions';
const statuses:Subscription['status'][]=['active','upcoming','expired','suspended','cancelled'];
const local=(value:string)=>{const date=new Date(value);date.setMinutes(date.getMinutes()-date.getTimezoneOffset());return date.toISOString().slice(0,16);};
export default function AdminSubscriptions(){
 const [rows,setRows]=useState<(Subscription & {customer_id:string})[]>([]),[filter,setFilter]=useState(''),[editing,setEditing]=useState<Subscription|null>(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const load=useCallback(async()=>{setLoading(true);setError('');try{const r=await api<{subscriptions:(Subscription & {customer_id:string})[]}>('/admin/subscriptions'+(filter?'?status='+filter:''));setRows(r.subscriptions);}catch(e){setError((e as Error).message);}finally{setLoading(false);}},[filter]);
 useEffect(()=>{void load();},[load]);
 async function process(){setBusy(true);setError('');try{const r=await api<{activated:number;expired:number}>('/admin/subscriptions/process',{});setNotice(`Processed subscriptions: ${r.activated} activated, ${r.expired} expired.`);await load();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function save(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(!editing)return;setBusy(true);setError('');try{const form=new FormData(e.currentTarget);await api('/admin/subscriptions/'+editing.id,{status:form.get('status'),ends_at:new Date(String(form.get('ends_at'))).toISOString(),device_limit:Number(form.get('device_limit')),account_reference:form.get('account_reference'),delivery_instructions:form.get('delivery_instructions')},'PUT');setEditing(null);setNotice('Subscription updated.');await load();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <div className="qs-admin-card"><div className="qs-admin-section-heading"><div><h2>Subscriptions</h2><p className="qs-admin-muted">Manage access, devices, expiry and renewal status.</p></div><button disabled={busy} onClick={()=>void process()}>Process expiry &amp; reminders</button></div>
  <label className="qs-admin-field"><span>Status</span><select value={filter} onChange={e=>setFilter(e.target.value)}><option value="">All subscriptions</option>{statuses.map(s=><option key={s}>{s}</option>)}</select></label>
  {error&&<p className="qs-admin-error" role="alert">{error}</p>}{notice&&<p className="qs-admin-success" role="status">{notice}</p>}
  {loading?<p>Loading subscriptions…</p>:!rows.length?<p className="qs-admin-muted">No subscriptions found.</p>:<div className="qs-admin-table-wrap"><table><thead><tr><th>Customer</th><th>Subscription</th><th>Status</th><th>Access period</th><th>Devices</th><th></th></tr></thead><tbody>{rows.map(s=><tr key={s.id}><td><small>{s.customer_id}</small></td><td><strong>{s.product_name}</strong><br/><small>{s.package_name}</small></td><td><span className="qs-admin-badge">{s.status}</span></td><td>{new Date(s.starts_at).toLocaleDateString()} – {new Date(s.ends_at).toLocaleDateString()}</td><td>{s.device_limit}</td><td><button onClick={()=>setEditing(s)}>Manage</button></td></tr>)}</tbody></table></div>}
  {editing&&<div className="qs-admin-overlay"><form className="qs-admin-editor" onSubmit={e=>void save(e)}><div className="qs-admin-section-heading"><h2>Manage subscription</h2><button type="button" onClick={()=>setEditing(null)} aria-label="Close editor">×</button></div><p>{editing.product_name} · {editing.package_name}</p><p className="qs-admin-muted">Payment confirmed {new Date(editing.payment_confirmed_at).toLocaleString()}</p><label className="qs-admin-field"><span>Status</span><select name="status" defaultValue={editing.status}>{statuses.map(s=><option key={s}>{s}</option>)}</select></label><label className="qs-admin-field"><span>Expiry</span><input name="ends_at" type="datetime-local" defaultValue={local(editing.ends_at)} required/></label><label className="qs-admin-field"><span>Device limit</span><input name="device_limit" type="number" min="1" max="100" defaultValue={editing.device_limit} required/></label><label className="qs-admin-field"><span>Assigned account reference</span><input name="account_reference" maxLength={160} defaultValue={editing.account_reference}/></label><label className="qs-admin-field"><span>Access instructions (never store passwords here)</span><textarea name="delivery_instructions" maxLength={2000} defaultValue={editing.delivery_instructions}/></label><button className="qs-admin-primary" disabled={busy}>{busy?'Saving…':'Save subscription'}</button></form></div>}
 </div>;
}
