import { useEffect, useState, type FormEvent } from 'react';
import { api } from '../utils/api';

type Settings={enabled:boolean;points_per_10_bdt:number;bdt_per_point:number;minimum_redemption:number;maximum_discount_percent:number;referral_reward:number;referred_reward:number;referral_wait_days:number;monthly_referral_limit:number};
type LoyaltyData={settings:Settings;summary:{outstanding:number;issued:number;redeemed:number;referrals:number;pendingReferrals:number};recent:{id:string;customer_id:string;kind:string;points:number;description:string;created_at:string;name?:string;contact?:string}[];referralRows:{id:string;referral_code:string;status:string;referrer_name?:string;referred_name?:string;created_at:string}[]};
export default function AdminLoyalty(){
 const [data,setData]=useState<LoyaltyData|null>(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);
 async function load(){setError('');try{setData(await api<LoyaltyData>('/admin/loyalty'));}catch(e){setError((e as Error).message);}}
 useEffect(()=>{void load();},[]);
 async function save(event:FormEvent){event.preventDefault();if(!data)return;setBusy(true);setError('');setNotice('');try{await api('/admin/loyalty/settings',data.settings,'PUT');setNotice('Rewards and referral settings saved.');await load();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 if(!data&&!error)return <div className="qs-admin-card qs-admin-empty">Loading rewards…</div>;
 return <div className="qs-admin-stack">{error&&<div className="qs-admin-error" role="alert">{error}</div>}{notice&&<div className="qs-admin-success" role="status">{notice}</div>}{data&&<>
  <div className="qs-admin-stat-grid">{[['Outstanding points',data.summary.outstanding],['Points issued',data.summary.issued],['Points redeemed',data.summary.redeemed],['All referrals',data.summary.referrals],['Pending referrals',data.summary.pendingReferrals]].map(([label,value])=><div className="qs-admin-card" key={label}><span>{label}</span><strong>{Number(value).toLocaleString()}</strong></div>)}</div>
  <form className="qs-admin-card qs-admin-form" onSubmit={save}><div className="qs-admin-section-heading"><div><h2>Rewards configuration</h2><p className="qs-admin-muted">Changes affect future earning, redemption and referral qualification. Reward value is fixed at 4 points = BDT 1.</p></div><label><input type="checkbox" checked={data.settings.enabled} onChange={e=>setData({...data,settings:{...data.settings,enabled:e.target.checked}})}/> Program enabled</label></div>
   <div className="qs-admin-grid">{([['Points per ৳10','points_per_10_bdt',0.1],['Minimum redemption','minimum_redemption',1],['Maximum discount %','maximum_discount_percent',1],['Referrer reward','referral_reward',1],['New customer reward','referred_reward',1],['Referral wait days','referral_wait_days',1],['Monthly referral limit','monthly_referral_limit',1]] as const).map(([label,key,step])=><label className="qs-admin-field" key={key}><span>{label}</span><input type="number" min="0" step={step} value={data.settings[key]} onChange={e=>setData({...data,settings:{...data.settings,[key]:Number(e.target.value)}})}/></label>)}</div><button disabled={busy}>{busy?'Saving…':'Save reward settings'}</button>
  </form>
  <form className="qs-admin-card qs-admin-form" onSubmit={async event=>{event.preventDefault();const form=event.currentTarget,values=new FormData(form);setBusy(true);setError('');try{await api('/admin/loyalty/adjust',{customerId:values.get('customerId'),points:Number(values.get('points')),reason:values.get('reason')});form.reset();setNotice('Points adjustment recorded in the audit log.');await load();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}><h2>Manual adjustment</h2><p className="qs-admin-muted">Use only for customer-service corrections. A reason is required and every change is audited.</p><div className="qs-admin-grid"><label className="qs-admin-field"><span>Customer UUID</span><input name="customerId" required pattern="[a-fA-F0-9-]{36}"/></label><label className="qs-admin-field"><span>Points (negative removes)</span><input name="points" type="number" min="-100000" max="100000" required/></label><label className="qs-admin-field"><span>Reason</span><input name="reason" minLength={5} maxLength={240} required/></label></div><button disabled={busy}>Record adjustment</button></form>
  <section className="qs-admin-card"><h2>Recent point activity</h2>{data.recent.length?<div className="qs-admin-table-wrap"><table><thead><tr><th>Customer</th><th>Event</th><th>Points</th><th>Date</th></tr></thead><tbody>{data.recent.map(row=><tr key={row.id}><td><strong>{row.name||'Customer'}</strong><small>{row.contact||row.customer_id}</small></td><td>{row.description}<small>{row.kind}</small></td><td><strong>{row.points>0?'+':''}{row.points}</strong></td><td>{new Date(row.created_at).toLocaleString()}</td></tr>)}</tbody></table></div>:<div className="qs-admin-empty">No reward activity yet.</div>}</section>
  <section className="qs-admin-card"><h2>Recent referrals</h2>{data.referralRows.length?<div className="qs-admin-table-wrap"><table><thead><tr><th>Code</th><th>Referrer</th><th>New customer</th><th>Status</th></tr></thead><tbody>{data.referralRows.map(row=><tr key={row.id}><td>{row.referral_code}</td><td>{row.referrer_name||'Customer'}</td><td>{row.referred_name||'Customer'}</td><td><span className="qs-admin-badge">{row.status}</span></td></tr>)}</tbody></table></div>:<div className="qs-admin-empty">No referrals yet.</div>}</section>
 </>}</div>;
}
